# Generated by Django 6.0.3 on 2026-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Add each topic separated by comma', null=True),
        ),
    ]
